### ISSUE TITLE
Github Action

### ISSUE THREAD

**Issue by numToStr** [numToStr/lemmy-help#19]
It would be nice to have a github action which can take args and lua files, and spit a help doc.

```yaml
name: lemmy-help

on: [push]

env:
  PROJECT_NAME: awesome-plugin

jobs:
  docs:
    runs-on: ubuntu-latest
    name: emmylua to vimdoc
    steps:
      - uses: actions/checkout@v2

      - name: Generating help
        id: lemmyhelp
        uses: numToStr/lemmy-help@main
        with:
          args: --prefix-class --prefix-alias
          path: |
            path/to/first/file.lua
            path/to/first/second.lua
            path/to/first/third.lua

      - name: Creating help file
        run: echo "${{ steps.lemmyhelp.outputs.doc }}" > ./doc/${PROJECT_NAME}.txt

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(docs): generate"
          branch: ${{ github.head_ref }}
```
